import Foundation
import Testing
@testable import SlideCore
import SwiftSlides

@Test func legacyAndUnknownRefused() { #expect(throws:SlideError.self) { try Presentation(data:Data([0xD0,0xCF,0x11,0xE0,0xA1,0xB1,0x1A,0xE1])) }; #expect(throws:SlideError.self) { try Presentation(data:Data("junk".utf8)) } }
@Test func malformedXMLRefused() throws { let data = try changedFixture { $0["ppt/slides/slide1.xml"] = Data("<p:sld xmlns:p=\"http://schemas.openxmlformats.org/presentationml/2006/main\"><p:cSld>".utf8) }; #expect(throws:SlideError.self) { try Presentation(data:data) } }
@Test func entityDeclarationsRefused() throws { let d = try changedFixture { $0["ppt/slides/slide1.xml"] = Data("<!DOCTYPE p:sld [<!ENTITY x 'secret'>]><p:sld/>".utf8) }; #expect(throws:SlideError.self) { try Presentation(data:d) } }
@Test func missingRelationshipRefused() throws { let d = try changedFixture { $0.removeValue(forKey:"ppt/slides/slide1.xml") }; #expect(throws:SlideError.self) { try Presentation(data:d) } }
@Test func foreignNamespaceSlideIsNotAccepted() throws { let d = try changedFixture { $0["ppt/slides/slide1.xml"] = $0["ppt/slides/slide1.xml"]!.replacingUTF8("http://schemas.openxmlformats.org/presentationml/2006/main","urn:foreign") }; #expect(throws:SlideError.self) { try Presentation(data:d) } }
@Test func unsafeRelationshipEscapeRefused() throws { let d = try changedFixture { $0["_rels/.rels"] = $0["_rels/.rels"]!.replacingUTF8("ppt/presentation.xml","../../outside.xml") }; #expect(throws:SlideError.self) { try Presentation(data:d) } }
@Test func duplicateShapeIDsRefused() throws { let d = try changedFixture { $0["ppt/slides/slide1.xml"] = $0["ppt/slides/slide1.xml"]!.replacingUTF8("id=\"3\"","id=\"2\"") }; #expect(throws:SlideError.self) { try Presentation(data:d) } }
@Test func compressedCRCChecked() throws { var d = try fixture("stored.pptx"); let index = try #require(d.range(of:Data("Fictional strategy".utf8))?.lowerBound); d[index] ^= 1; #expect(throws:SlideError.self) { try Presentation(data:d) } }
@Test func zipLimitsAndXMLLimits() throws { let d = try fixture(); #expect(throws:SlideError.self) { try Presentation(data:d,options:.init(limits:.init(maxEntries:2))) }; #expect(throws:SlideError.self) { try Presentation(data:d,options:.init(limits:.init(maxExpandedBytes:4))) }; #expect(throws:SlideError.self) { try Presentation(data:d,options:.init(limits:.init(maxXMLDepth:2))) }; #expect(throws:SlideError.self) { try Presentation(data:d,options:.init(limits:.init(maxXMLNodes:2))) } }
@Test func dataSlicesAndTruncatedArchive() throws { let d = try fixture(); var padded = Data([0,1]); padded.append(d); #expect(try Presentation(data:padded.dropFirst(2)).slides.count == 2); #expect(throws:SlideError.self) { try Presentation(data:d.dropLast()) } }
@Test func gridAlignmentAndDistribution() throws { let cells = try Layout.grid(in:.init(x:20,y:20,width:880,height:200),rows:1,columns:3,gap:20,insets:.init(10)); #expect(cells.count == 3); #expect(cells[0].x == 30); #expect(abs(cells[2].maxX-890) < 0.001); var elements = [Element(frame:.init(x:10,y:20,width:40,height:30)),Element(frame:.init(x:50,y:40,width:60,height:50))]; Layout.align(&elements,to:.bottom,in:.init(x:0,y:0,width:400,height:300)); #expect(elements[0].frame?.maxY == 300); #expect(elements[1].frame?.maxY == 300); try Layout.distribute(&elements,along:.horizontal,in:.init(x:20,y:0,width:300,height:100)); #expect(elements[0].frame?.x == 20); #expect(elements[1].frame?.maxX == 320) }
@Test func invalidLayoutRefused() { #expect(throws:SlideError.self) { try Layout.grid(in:.init(x:0,y:0,width:10,height:10),rows:0,columns:2) }; #expect(throws:SlideError.self) { try Layout.grid(in:.init(x:0,y:0,width:10,height:10),rows:2,columns:2,gap:20) } }
@Test func lineDirectionAndRichParagraphs() throws { var s = Slide(); s.addLine(from:(300,200),to:(100,50),stroke:.init(endArrow:.stealth)); s.elements.append(Element(frame:.init(x:20,y:20,width:400,height:200),text:.init(paragraphs:[.init(runs:[.init("Bold",style:.init(bold:true)),.init("\nItalic",style:.init(italic:true))],style:.init(alignment:.right,level:1,leftMargin:18,indent:-10,spaceAfter:8,lineSpacing:1.2,bullet:.character("•")))]))); let p = try Presentation(data:Presentation(slides:[s]).data()); #expect(p.slides[0].elements[0].flipHorizontal); #expect(p.slides[0].elements[0].flipVertical); #expect(p.slides[0].elements[1].text?.plainText == "Bold\nItalic"); #expect(p.slides[0].elements[1].text?.paragraphs[0].style.bullet == .character("•")) }
extension Data { func replacingUTF8(_ a: String,_ b: String) -> Data { Data(String(decoding:self,as:UTF8.self).replacingOccurrences(of:a,with:b).utf8) } }
