// docs/capabilities.jsonから生成。直接編集せずscripts/build-capabilities.pyを使う。
import SlideCore

enum PPTXFeatureCapabilities {
    private static let evidence: [CapabilityEvidence] = [
        .init(id: "E01", fixture: "python-pptx.pptx", fixtureSHA256: "de176a193e19d3670670e36b2f29c6301ad6d444083e61416d3e631985418d40", test: "independentProducerOracle", scope: "python-pptxが生成・再読した期待値と本文、直接フォント、段落、リンクを比較。実効外観は含まない。"),
        .init(id: "E02", fixture: "strict.pptx", fixtureSHA256: "d2faa745a19ec87aa7e906599c6bf07357dd669fc3ca09245acec2156607d941", test: "readContainers", scope: "python-pptx由来fixtureの名前空間をStrictへ置換した資料。2枚の順序と本文を確認。Strict producerや全スキーマの検証ではない。"),
        .init(id: "E03", fixture: "python-pptx.pptx", fixtureSHA256: "de176a193e19d3670670e36b2f29c6301ad6d444083e61416d3e631985418d40", test: "geometryImagesGroupsTablesAndNotes", scope: "図形座標、非結合表のセル本文、画像bytes、グループ、ノートを確認。"),
        .init(id: "E04", fixture: "python-pptx.pptx", fixtureSHA256: "de176a193e19d3670670e36b2f29c6301ad6d444083e61416d3e631985418d40", test: "opaqueChartIsWarnedAndPreserved", scope: "棒チャートのgraphicFrameをopaqueとして読み、元XMLと警告を確認。追加されたcache投影の検証は別証拠。"),
        .init(id: "E05", fixture: "python-pptx.pptx", fixtureSHA256: "de176a193e19d3670670e36b2f29c6301ad6d444083e61416d3e631985418d40", test: "noOpIsByteIdentical", scope: "指定fixtureの未変更保存が入力全bytesと一致することを確認。編集保存の任意依存は検証しない。"),
        .init(id: "E06", fixture: "strict.pptx", fixtureSHA256: "d2faa745a19ec87aa7e906599c6bf07357dd669fc3ca09245acec2156607d941", test: "noOpIsByteIdentical", scope: "指定fixtureの未変更保存が入力全bytesと一致することを確認。編集保存の任意依存は検証しない。"),
        .init(id: "E07", fixture: "macro.pptm", fixtureSHA256: "4ad887cd5337aa89f666766bc6bf69c834c2d0ebb153960b92a5c4d56c52846c", test: "noOpIsByteIdentical", scope: "指定fixtureの未変更保存が入力全bytesと一致することを確認。編集保存の任意依存は検証しない。"),
        .init(id: "E08", fixture: "unknown.pptx", fixtureSHA256: "742580bb39cc77a600330c3628ff08b067a1fdfec6d24e7551faf69567addbbe", test: "noOpIsByteIdentical", scope: "指定fixtureの未変更保存が入力全bytesと一致することを確認。編集保存の任意依存は検証しない。"),
        .init(id: "E09", fixture: "unknown.pptx", fixtureSHA256: "742580bb39cc77a600330c3628ff08b067a1fdfec6d24e7551faf69567addbbe", test: "editTextPreservesOtherPartsAndNamespaces", scope: "本文1箇所を書き換え、無関係の圧縮済パーツ、未知拡張XML、namespaceを保持。書換え警告とstrict拒否を確認。"),
        .init(id: "E10", fixture: "strict.pptx", fixtureSHA256: "d2faa745a19ec87aa7e906599c6bf07357dd669fc3ca09245acec2156607d941", test: "strictNamespaceEdit", scope: "既存要素のy座標変更と本文保持を再読で確認。Strictでの新規スライド追加は含まない。"),
        .init(id: "E11", fixture: "python-pptx.pptx", fixtureSHA256: "de176a193e19d3670670e36b2f29c6301ad6d444083e61416d3e631985418d40", test: "frameEditPreservesRichTextAndChart", scope: "既知テキスト図形のx座標だけを変更し、rich textと別スライドのチャートXMLを保持。"),
        .init(id: "E12", fixture: "macro.pptm", fixtureSHA256: "4ad887cd5337aa89f666766bc6bf69c834c2d0ebb153960b92a5c4d56c52846c", test: "macrosPreserved", scope: "metadata編集後に架空の非実行VBA bytesが一致することと、PPTXへの暗黙変換拒否を確認。実マクロ動作は未検証。"),
        .init(id: "E13", fixture: "python-pptx.pptx", fixtureSHA256: "de176a193e19d3670670e36b2f29c6301ad6d444083e61416d3e631985418d40", test: "editedImageRetainsPackage", scope: "既存画像を架空PNG bytesと代替文へ差し替え、保存後の代替文を再読で確認。"),
        .init(id: "E14", fixture: "python-pptx.pptx", fixtureSHA256: "de176a193e19d3670670e36b2f29c6301ad6d444083e61416d3e631985418d40", test: "signedPackageOnlyNoOpAllowed", scope: "fixtureに架空署名パーツを追加し、未変更全bytes一致を確認。暗号署名のvalidityは未検証。"),
        .init(id: "E15", fixture: "python-pptx.pptx", fixtureSHA256: "de176a193e19d3670670e36b2f29c6301ad6d444083e61416d3e631985418d40", test: "signedPackageOnlyNoOpAllowed", scope: "fixtureに架空署名パーツを追加し、metadata編集保存の拒否を確認。"),
        .init(id: "E16", fixture: "python-pptx.pptx", fixtureSHA256: "de176a193e19d3670670e36b2f29c6301ad6d444083e61416d3e631985418d40", test: "opaqueMutationAndThemeMutationRefused", scope: "チャートopaque要素の位置変更と既存テーマの変更をそれぞれ拒否することを確認。"),
        .init(id: "E17", fixture: "fixture.png", fixtureSHA256: "b2570ba9eea72bc56a277aca4f7dce333a815bcf68c1407683576579a93e88f9", test: "createRichPresentation", scope: "新規文字・図形・画像・非結合表・ノートを生成してSwiftSlidesで再読。画像入力は架空の1pixel PNG。実アプリ検証の証拠ではない。"),
        .init(id: "E18", fixture: "python-pptx.pptx", fixtureSHA256: "de176a193e19d3670670e36b2f29c6301ad6d444083e61416d3e631985418d40", test: "inventoryListsLocatedReferencesAndIdentities", scope: "fixtureにtimingと架空の未知参照を追加し、位置・原本identity・既知/未知を確認。全形式の依存解釈ではない。"),
        .init(id: "E19", fixture: "python-pptx.pptx", fixtureSHA256: "de176a193e19d3670670e36b2f29c6301ad6d444083e61416d3e631985418d40", test: "savePlanCopiesOriginalAndLocatesPatch", scope: "未変更計画のbyte一致とcopy actions、既存要素の位置変更のpatch計画・再読を検査。出力Dataを計画時に生成する。"),
        .init(id: "E20", fixture: "python-pptx.pptx", fixtureSHA256: "de176a193e19d3670670e36b2f29c6301ad6d444083e61416d3e631985418d40", test: "duplicatePreservesNotesChartAssetsAndLocalReferences", scope: "notes/chart/embedded Workbookを独立partへ複製し、画像共有、原本圧縮payload保持、独立notes編集を確認。チャートの新規生成・再計算ではない。"),
        .init(id: "E21", fixture: "python-pptx.pptx", fixtureSHA256: "de176a193e19d3670670e36b2f29c6301ad6d444083e61416d3e631985418d40", test: "importRebasesMasterAssetsAndRequiresSlideLinkMapping", scope: "fixtureのrun linkを別slideへ変更し、新規文書へimport。明示対応表、layout/master/assetsの移植、notes、保存計画とstale拒否を確認。"),
        .init(id: "E22", fixture: "strict.pptx", fixtureSHA256: "d2faa745a19ec87aa7e906599c6bf07357dd669fc3ca09245acec2156607d941", test: "cloneRefusesUnknownConflictingMastersAndProfiles", scope: "名前空間をStrictへ変更したfixture内の1枚複製を再読。Strict producerやStrict新規生成の証拠ではない。"),
        .init(id: "E23", fixture: "macro.pptm", fixtureSHA256: "4ad887cd5337aa89f666766bc6bf69c834c2d0ebb153960b92a5c4d56c52846c", test: "macroDuplicatePreservesVBAAndCloneCancellationIsAtomic", scope: "架空VBAを持つPPTMの同文書内複製と元VBA圧縮payload保持。マクロの実行・別資料取り込みは行わない。"),
        .init(id: "E27", fixture: "reading-models.pptx", fixtureSHA256: "101f63e92c97fcf51aad5922d98483a2c6c7c58d7dae78cdec9533082818f9d4", test: "unitSpacingFieldsAndSourceStyles", scope: "points/percentage・0・field ID/type/cache/pPr・default/list/masterの直接値。日時localeの完全互換や実効継承を含まない。"),
        .init(id: "E28", fixture: "reading-models.pptx", fixtureSHA256: "101f63e92c97fcf51aad5922d98483a2c6c7c58d7dae78cdec9533082818f9d4", test: "colorGeometryAndOuterShadowProjection", scope: "順序付き色変換と透明度系、数値Bezier/close、外側の影・effectRef。色空間計算・guide/arc評価・合成を含まない。"),
        .init(id: "E29", fixture: "reading-models.pptx", fixtureSHA256: "101f63e92c97fcf51aad5922d98483a2c6c7c58d7dae78cdec9533082818f9d4", test: "inheritedPartsTablesChartsAndSavedDiagram", scope: "master/layoutの要素・表・画像、2D barの疎cache/literal・数式・軸・タイトル・凡例、保存済みdiagram drawing。描画・Workbook再計算・自動配置を含まない。"),
        .init(id: "E30", fixture: "reading-models.pptx", fixtureSHA256: "101f63e92c97fcf51aad5922d98483a2c6c7c58d7dae78cdec9533082818f9d4", test: "fieldAndSpacingEditsKeepRunsAndStrictNamespace", scope: "既存の単位付き間隔とfieldキャッシュを明示編集し、run境界・listStyle・field pPrの名前空間を再読。未知書式の任意編集を含まない。"),
        .init(id: "E31", fixture: "reading-models.pptx", fixtureSHA256: "101f63e92c97fcf51aad5922d98483a2c6c7c58d7dae78cdec9533082818f9d4", test: "projectionPreservesSourceAndRefusesUnsupportedEdits", scope: "自由曲線・効果・chart cache投影の変更と変換色の書換えを拒否。既存位置編集では原本を維持。"),
        .init(id: "E32", fixture: "reading-models-strict.pptx", fixtureSHA256: "10452311bd82b52f83c3106709849673a41e0a2adaeecb0c8676fcec4fc46523", test: "unitSpacingFieldsAndSourceStyles", scope: "points/percentage・0・field ID/type/cache/pPr・default/list/masterの直接値。日時localeの完全互換や実効継承を含まない。 Strictは合成名前空間変種でありStrict producerの証拠ではない。"),
        .init(id: "E33", fixture: "reading-models-strict.pptx", fixtureSHA256: "10452311bd82b52f83c3106709849673a41e0a2adaeecb0c8676fcec4fc46523", test: "colorGeometryAndOuterShadowProjection", scope: "順序付き色変換と透明度系、数値Bezier/close、外側の影・effectRef。色空間計算・guide/arc評価・合成を含まない。 Strictは合成名前空間変種でありStrict producerの証拠ではない。"),
        .init(id: "E34", fixture: "reading-models-strict.pptx", fixtureSHA256: "10452311bd82b52f83c3106709849673a41e0a2adaeecb0c8676fcec4fc46523", test: "inheritedPartsTablesChartsAndSavedDiagram", scope: "master/layoutの要素・表・画像、2D barの疎cache/literal・数式・軸・タイトル・凡例、保存済みdiagram drawing。描画・Workbook再計算・自動配置を含まない。 Strictは合成名前空間変種でありStrict producerの証拠ではない。"),
        .init(id: "E35", fixture: "reading-models-strict.pptx", fixtureSHA256: "10452311bd82b52f83c3106709849673a41e0a2adaeecb0c8676fcec4fc46523", test: "fieldAndSpacingEditsKeepRunsAndStrictNamespace", scope: "既存の単位付き間隔とfieldキャッシュを明示編集し、run境界・listStyle・field pPrの名前空間を再読。未知書式の任意編集を含まない。 Strictは合成名前空間変種でありStrict producerの証拠ではない。"),
        .init(id: "E36", fixture: "reading-models-strict.pptx", fixtureSHA256: "10452311bd82b52f83c3106709849673a41e0a2adaeecb0c8676fcec4fc46523", test: "projectionPreservesSourceAndRefusesUnsupportedEdits", scope: "自由曲線・効果・chart cache投影の変更と変換色の書換えを拒否。既存位置編集では原本を維持。 Strictは合成名前空間変種でありStrict producerの証拠ではない。"),
        .init(id: "E37", fixture: "advanced-reading.pptx", fixtureSHA256: "68566f641a4c7b145c62d2931b475fa62cbde889bc0e0cd7bd39e2b51fe0707c", test: "advancedFillsCropAndCellBorders", scope: "架空のgradient・pattern・画像塗り・srcRect・個別罫線の直接値と未変更bytesを照合。Strict版は名前空間置換でproducer検証ではない。"),
        .init(id: "E38", fixture: "advanced-reading.pptx", fixtureSHA256: "68566f641a4c7b145c62d2931b475fa62cbde889bc0e0cd7bd39e2b51fe0707c", test: "transitionsTimingMediaAndComments", scope: "架空のpush/進行時刻/timing/埋込音声参照/従来コメントと選択readerを照合。再生なし。"),
        .init(id: "E39", fixture: "advanced-reading.pptx", fixtureSHA256: "68566f641a4c7b145c62d2931b475fa62cbde889bc0e0cd7bd39e2b51fe0707c", test: "advancedProjectionPreservesUnrelatedEditsAndRefusesMutations", scope: "位置編集で無関係な原本投影を保持し、追加塗り・crop・media・timing・遷移・コメント・拡張投影の変更保存を拒否。"),
        .init(id: "E40", fixture: "advanced-reading-strict.pptx", fixtureSHA256: "93109eabdf600d5fffcf319977e06da6c431b75a90eeb9a2e40c8d0430d0bb45", test: "advancedFillsCropAndCellBorders", scope: "架空のgradient・pattern・画像塗り・srcRect・個別罫線の直接値と未変更bytesを照合。Strict版は名前空間置換でproducer検証ではない。"),
        .init(id: "E41", fixture: "advanced-reading-strict.pptx", fixtureSHA256: "93109eabdf600d5fffcf319977e06da6c431b75a90eeb9a2e40c8d0430d0bb45", test: "transitionsTimingMediaAndComments", scope: "架空のpush/進行時刻/timing/埋込音声参照/従来コメントと選択readerを照合。再生なし。"),
        .init(id: "E42", fixture: "advanced-reading-strict.pptx", fixtureSHA256: "93109eabdf600d5fffcf319977e06da6c431b75a90eeb9a2e40c8d0430d0bb45", test: "advancedProjectionPreservesUnrelatedEditsAndRefusesMutations", scope: "位置編集で無関係な原本投影を保持し、追加塗り・crop・media・timing・遷移・コメント・拡張投影の変更保存を拒否。"),
        .init(id: "E44", fixture: "libreoffice-advanced.pptx", fixtureSHA256: "df1deff17ca8992893e702c4a330207fb55e8edb7cc8ef39b88bd130952457a0", test: "libreOfficeAdvancedOutputReadsProducerValues", scope: "LibreOffice 26.2.3.2でadvanced-reading.pptxをPPTX再保存。gradient/pattern/画像塗り/timing/音声/従来コメントを再読し、未変更bytes一致。元入力との外観一致は未測定。"),
        .init(id: "E45", fixture: "advanced-reading.pptx", fixtureSHA256: "68566f641a4c7b145c62d2931b475fa62cbde889bc0e0cd7bd39e2b51fe0707c", test: "modernCommentsAndExternalVideoRetainDescriptors", scope: "fixtureの音声参照を外部動画へ、新comments relationship URIと根要素へ置換。外部URLを取得せず参照を投影、新コメントXMLと診断を保持。"),
    ]

    static func features(for format: PresentationFormat) -> [FeatureCapability] {
        switch format {
        case .pptm:
            return [
                .init(feature: "IO-008", profile: .ooxmlTransitional, operation: .preserve, status: .supported, evidence: [evidence[6]], notes: "未変更保存に限って全bytes一致。編集保存の可否は別に検査する。"),
                .init(feature: "SEC-005", profile: .ooxmlTransitional, operation: .edit, status: .preserveOnly, evidence: [evidence[11]], notes: "metadata変更時に元VBA bytesを保持。実マクロの解釈・実行・新規生成・除去は提供しない。"),
                .init(feature: "SEC-005", profile: .ooxmlTransitional, operation: .preserve, status: .partial, evidence: [evidence[6]], notes: "架空VBAパーツを未変更で全bytes保持。実マクロの動作を証明しない。"),
                .init(feature: "DOC-004", profile: .ooxmlTransitional, operation: .edit, status: .partial, evidence: [evidence[22]], notes: "同文書内の複製とVBA原本保持。別資料へのマクロ移植は拒否。"),
            ]
        case .pptx:
            return [
                .init(feature: "TXT-001", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[0]], notes: "Unicode本文の直接値。高度な文字制御は未検証。"),
                .init(feature: "TXT-003", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[0]], notes: "直接font family/sizeと一部書式。継承フォント・言語全体は未解決。"),
                .init(feature: "TXT-008", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[0]], notes: "直接指定の段落alignment。全indent/margin条件は未検証。"),
                .init(feature: "PKG-004", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[0]], notes: "Transitional fixtureの読取。全schema互換性の保証ではない。"),
                .init(feature: "PKG-004", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[1]], notes: "名前空間変種の基本本文読取。未検証のStrict機能は含まない。"),
                .init(feature: "IMG-001", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[2]], notes: "埋込PNGの参照と必要時bytes展開。全画像形式の描画は未検証。"),
                .init(feature: "TBL-001", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[2]], notes: "非結合表のセル読取。高度なtable styleは未解決。"),
                .init(feature: "OBJ-011", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[3]], notes: "チャートをopaque要素として位置・元XML・警告付きで読取。意味は未解釈。"),
                .init(feature: "CHT-001", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[3], evidence[25]], notes: "master/layoutの要素・表・画像、2D barの疎cache/literal・数式・軸・タイトル・凡例、保存済みdiagram drawing。描画・Workbook再計算・自動配置を含まない。"),
                .init(feature: "IO-008", profile: .ooxmlTransitional, operation: .preserve, status: .supported, evidence: [evidence[4]], notes: "未変更保存に限って全bytes一致。編集保存の可否は別に検査する。"),
                .init(feature: "IO-008", profile: .ooxmlStrict, operation: .preserve, status: .supported, evidence: [evidence[5]], notes: "未変更保存に限って全bytes一致。編集保存の可否は別に検査する。"),
                .init(feature: "CHT-001", profile: .ooxmlTransitional, operation: .preserve, status: .partial, evidence: [evidence[4]], notes: "棒チャートを含むfixtureの未変更全bytes保持。編集・変換・再生は含まない。"),
                .init(feature: "OBJ-009", profile: .ooxmlTransitional, operation: .preserve, status: .partial, evidence: [evidence[7]], notes: "架空拡張XMLとopaque binaryを含む未変更資料の全bytes保持。"),
                .init(feature: "TXT-002", profile: .ooxmlTransitional, operation: .edit, status: .partial, evidence: [evidence[8]], notes: "文字段落を再構成する本文差替え。未対応書式の書換え警告を返しstrict保存は拒否する。"),
                .init(feature: "OBJ-009", profile: .ooxmlTransitional, operation: .edit, status: .partial, evidence: [evidence[8]], notes: "本文の局所編集時に無関係の拡張を保全。未知参照の任意編集を許可しない。"),
                .init(feature: "PKG-004", profile: .ooxmlStrict, operation: .edit, status: .partial, evidence: [evidence[9]], notes: "既存要素の位置変更のみを確認。Strict新規生成・スライド追加は提供しない。"),
                .init(feature: "CHT-001", profile: .ooxmlTransitional, operation: .edit, status: .preserveOnly, evidence: [evidence[10]], notes: "別スライドの既知要素を位置変更してもチャートXMLを保持。チャートそのものの編集ではない。"),
                .init(feature: "IMG-001", profile: .ooxmlTransitional, operation: .edit, status: .partial, evidence: [evidence[12]], notes: "既存PNG画像の差替えと代替文を確認。crop/effectの変更は含まない。"),
                .init(feature: "SEC-006", profile: .ooxmlTransitional, operation: .preserve, status: .partial, evidence: [evidence[13]], notes: "署名パーツを含む未変更資料のbytes保持のみ。署名の暗号検証は提供しない。"),
                .init(feature: "SEC-006", profile: .ooxmlTransitional, operation: .edit, status: .unsupported, evidence: [evidence[14]], notes: "署名パーツがある資料の編集保存を拒否する。"),
                .init(feature: "OBJ-011", profile: .ooxmlTransitional, operation: .edit, status: .unsupported, evidence: [evidence[15]], notes: "元opaque要素の変更保存は拒否する。"),
                .init(feature: "TXT-001", profile: .ooxmlTransitional, operation: .create, status: .partial, evidence: [evidence[16]], notes: "新規PPTXの基本直接値を生成。対応する限定モデルの自己再読を検証し、高度機能は含まない。"),
                .init(feature: "IMG-001", profile: .ooxmlTransitional, operation: .create, status: .partial, evidence: [evidence[16]], notes: "新規PPTXの基本直接値を生成。対応する限定モデルの自己再読を検証し、高度機能は含まない。"),
                .init(feature: "TBL-001", profile: .ooxmlTransitional, operation: .create, status: .partial, evidence: [evidence[16]], notes: "新規PPTXの基本直接値を生成。対応する限定モデルの自己再読を検証し、高度機能は含まない。"),
                .init(feature: "MTA-008", profile: .ooxmlTransitional, operation: .inspect, status: .partial, evidence: [evidence[17]], notes: "原本XML/relationshipの参照と未知scopeを列挙。非XML内部・モデル変更後のgraphは未解釈。"),
                .init(feature: "IO-009", profile: .ooxmlTransitional, operation: .edit, status: .partial, evidence: [evidence[18]], notes: "現行writerを使う事前エンコード計画。source/model/options変更を拒否。遅延file監視・全理由の収集は未実装。"),
                .init(feature: "DOC-004", profile: .ooxmlTransitional, operation: .edit, status: .partial, evidence: [evidence[19], evidence[20]], notes: "同寸法・同profileで原本を複製・取り込み。未知参照、競合notes master、独自table styleの別資料取り込みは拒否。"),
                .init(feature: "DOC-004", profile: .ooxmlStrict, operation: .edit, status: .partial, evidence: [evidence[21]], notes: "同じStrict原本内の複製のみ確認。異profileの取り込みとStrict新規生成は未対応。"),
                .init(feature: "TXT-009", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[23]], notes: "points/percentage・0・field ID/type/cache/pPr・default/list/masterの直接値。日時localeの完全互換や実効継承を含まない。"),
                .init(feature: "TXT-020", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[23]], notes: "points/percentage・0・field ID/type/cache/pPr・default/list/masterの直接値。日時localeの完全互換や実効継承を含まない。"),
                .init(feature: "PNT-002", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[24]], notes: "順序付き色変換と透明度系、数値Bezier/close、外側の影・effectRef。色空間計算・guide/arc評価・合成を含まない。"),
                .init(feature: "GEO-004", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[24]], notes: "順序付き色変換と透明度系、数値Bezier/close、外側の影・effectRef。色空間計算・guide/arc評価・合成を含まない。"),
                .init(feature: "PNT-009", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[24]], notes: "順序付き色変換と透明度系、数値Bezier/close、外側の影・effectRef。色空間計算・guide/arc評価・合成を含まない。"),
                .init(feature: "STY-001", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[25]], notes: "master/layoutの要素・表・画像、2D barの疎cache/literal・数式・軸・タイトル・凡例、保存済みdiagram drawing。描画・Workbook再計算・自動配置を含まない。"),
                .init(feature: "CHT-004", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[25]], notes: "master/layoutの要素・表・画像、2D barの疎cache/literal・数式・軸・タイトル・凡例、保存済みdiagram drawing。描画・Workbook再計算・自動配置を含まない。"),
                .init(feature: "CHT-006", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[25]], notes: "master/layoutの要素・表・画像、2D barの疎cache/literal・数式・軸・タイトル・凡例、保存済みdiagram drawing。描画・Workbook再計算・自動配置を含まない。"),
                .init(feature: "CHT-007", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[25]], notes: "master/layoutの要素・表・画像、2D barの疎cache/literal・数式・軸・タイトル・凡例、保存済みdiagram drawing。描画・Workbook再計算・自動配置を含まない。"),
                .init(feature: "OBJ-001", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[25]], notes: "master/layoutの要素・表・画像、2D barの疎cache/literal・数式・軸・タイトル・凡例、保存済みdiagram drawing。描画・Workbook再計算・自動配置を含まない。"),
                .init(feature: "TXT-009", profile: .ooxmlTransitional, operation: .edit, status: .partial, evidence: [evidence[26]], notes: "既存の単位付き間隔とfieldキャッシュを明示編集し、run境界・listStyle・field pPrの名前空間を再読。未知書式の任意編集を含まない。"),
                .init(feature: "TXT-020", profile: .ooxmlTransitional, operation: .edit, status: .partial, evidence: [evidence[26]], notes: "既存の単位付き間隔とfieldキャッシュを明示編集し、run境界・listStyle・field pPrの名前空間を再読。未知書式の任意編集を含まない。"),
                .init(feature: "PNT-002", profile: .ooxmlTransitional, operation: .edit, status: .unsupported, evidence: [evidence[27]], notes: "自由曲線・効果・chart cache投影の変更と変換色の書換えを拒否。既存位置編集では原本を維持。"),
                .init(feature: "GEO-004", profile: .ooxmlTransitional, operation: .edit, status: .unsupported, evidence: [evidence[27]], notes: "自由曲線・効果・chart cache投影の変更と変換色の書換えを拒否。既存位置編集では原本を維持。"),
                .init(feature: "PNT-009", profile: .ooxmlTransitional, operation: .edit, status: .unsupported, evidence: [evidence[27]], notes: "自由曲線・効果・chart cache投影の変更と変換色の書換えを拒否。既存位置編集では原本を維持。"),
                .init(feature: "CHT-004", profile: .ooxmlTransitional, operation: .edit, status: .unsupported, evidence: [evidence[27]], notes: "自由曲線・効果・chart cache投影の変更と変換色の書換えを拒否。既存位置編集では原本を維持。"),
                .init(feature: "TXT-009", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[28]], notes: "points/percentage・0・field ID/type/cache/pPr・default/list/masterの直接値。日時localeの完全互換や実効継承を含まない。"),
                .init(feature: "TXT-020", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[28]], notes: "points/percentage・0・field ID/type/cache/pPr・default/list/masterの直接値。日時localeの完全互換や実効継承を含まない。"),
                .init(feature: "PNT-002", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[29]], notes: "順序付き色変換と透明度系、数値Bezier/close、外側の影・effectRef。色空間計算・guide/arc評価・合成を含まない。"),
                .init(feature: "GEO-004", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[29]], notes: "順序付き色変換と透明度系、数値Bezier/close、外側の影・effectRef。色空間計算・guide/arc評価・合成を含まない。"),
                .init(feature: "PNT-009", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[29]], notes: "順序付き色変換と透明度系、数値Bezier/close、外側の影・effectRef。色空間計算・guide/arc評価・合成を含まない。"),
                .init(feature: "STY-001", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[30]], notes: "master/layoutの要素・表・画像、2D barの疎cache/literal・数式・軸・タイトル・凡例、保存済みdiagram drawing。描画・Workbook再計算・自動配置を含まない。"),
                .init(feature: "CHT-001", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[30]], notes: "master/layoutの要素・表・画像、2D barの疎cache/literal・数式・軸・タイトル・凡例、保存済みdiagram drawing。描画・Workbook再計算・自動配置を含まない。"),
                .init(feature: "CHT-004", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[30]], notes: "master/layoutの要素・表・画像、2D barの疎cache/literal・数式・軸・タイトル・凡例、保存済みdiagram drawing。描画・Workbook再計算・自動配置を含まない。"),
                .init(feature: "CHT-006", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[30]], notes: "master/layoutの要素・表・画像、2D barの疎cache/literal・数式・軸・タイトル・凡例、保存済みdiagram drawing。描画・Workbook再計算・自動配置を含まない。"),
                .init(feature: "CHT-007", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[30]], notes: "master/layoutの要素・表・画像、2D barの疎cache/literal・数式・軸・タイトル・凡例、保存済みdiagram drawing。描画・Workbook再計算・自動配置を含まない。"),
                .init(feature: "OBJ-001", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[30]], notes: "master/layoutの要素・表・画像、2D barの疎cache/literal・数式・軸・タイトル・凡例、保存済みdiagram drawing。描画・Workbook再計算・自動配置を含まない。"),
                .init(feature: "TXT-009", profile: .ooxmlStrict, operation: .edit, status: .partial, evidence: [evidence[31]], notes: "既存の単位付き間隔とfieldキャッシュを明示編集し、run境界・listStyle・field pPrの名前空間を再読。未知書式の任意編集を含まない。"),
                .init(feature: "TXT-020", profile: .ooxmlStrict, operation: .edit, status: .partial, evidence: [evidence[31]], notes: "既存の単位付き間隔とfieldキャッシュを明示編集し、run境界・listStyle・field pPrの名前空間を再読。未知書式の任意編集を含まない。"),
                .init(feature: "PNT-002", profile: .ooxmlStrict, operation: .edit, status: .unsupported, evidence: [evidence[32]], notes: "自由曲線・効果・chart cache投影の変更と変換色の書換えを拒否。既存位置編集では原本を維持。"),
                .init(feature: "GEO-004", profile: .ooxmlStrict, operation: .edit, status: .unsupported, evidence: [evidence[32]], notes: "自由曲線・効果・chart cache投影の変更と変換色の書換えを拒否。既存位置編集では原本を維持。"),
                .init(feature: "PNT-009", profile: .ooxmlStrict, operation: .edit, status: .unsupported, evidence: [evidence[32]], notes: "自由曲線・効果・chart cache投影の変更と変換色の書換えを拒否。既存位置編集では原本を維持。"),
                .init(feature: "CHT-004", profile: .ooxmlStrict, operation: .edit, status: .unsupported, evidence: [evidence[32]], notes: "自由曲線・効果・chart cache投影の変更と変換色の書換えを拒否。既存位置編集では原本を維持。"),
                .init(feature: "PNT-004", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[33], evidence[39]], notes: "linear角度・path種類・stop順/色を保持。stop省略を継承補完せず、XML・診断を返す。"),
                .init(feature: "PNT-005", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[33], evidence[39]], notes: "pattern presetと前景/背景色。描画なし。"),
                .init(feature: "PNT-006", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[33], evidence[39]], notes: "内部/外部画像参照、crop、tileの有無、stretch詳細はXML。外部取得なし。"),
                .init(feature: "IMG-003", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[33]], notes: "srcRectの直接倍率と負値。形状mask・描画なし。"),
                .init(feature: "TBL-004", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[33]], notes: "四辺と対角線の直接stroke/noFill・XML。table styleによる実効罫線は未計算。"),
                .init(feature: "ANI-001", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[34], evidence[39]], notes: "直接効果名・namespace、方向等はXML。固有効果の再生なし。"),
                .init(feature: "ANI-002", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[34]], notes: "速度・クリック進行・進行時刻と拡張duration(ms)。未指定を補完しない。"),
                .init(feature: "ANI-005", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[34], evidence[39]], notes: "timingのnamespace付き木・属性・対象shape ID。トリガー/タイムライン評価なし。"),
                .init(feature: "MED-001", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[34], evidence[39], evidence[40]], notes: "audio/video/Office mediaの内部/外部参照とcontent type。埋込音声と外部動画の架空検査。再生なし。"),
                .init(feature: "REV-001", profile: .ooxmlTransitional, operation: .read, status: .partial, evidence: [evidence[34], evidence[39]], notes: "従来コメントの本文・作者・日時字句・位置(pt)とXML。返信・mentions等の新形式は未解釈。"),
                .init(feature: "PNT-004", profile: .ooxmlTransitional, operation: .edit, status: .unsupported, evidence: [evidence[35]], notes: "追加投影は読取専用。変更・新規保存を拒否し、未変更部分は保持。"),
                .init(feature: "PNT-005", profile: .ooxmlTransitional, operation: .edit, status: .unsupported, evidence: [evidence[35]], notes: "追加投影は読取専用。変更・新規保存を拒否し、未変更部分は保持。"),
                .init(feature: "PNT-006", profile: .ooxmlTransitional, operation: .edit, status: .unsupported, evidence: [evidence[35]], notes: "追加投影は読取専用。変更・新規保存を拒否し、未変更部分は保持。"),
                .init(feature: "IMG-003", profile: .ooxmlTransitional, operation: .edit, status: .unsupported, evidence: [evidence[35]], notes: "追加投影は読取専用。変更・新規保存を拒否し、未変更部分は保持。"),
                .init(feature: "ANI-001", profile: .ooxmlTransitional, operation: .edit, status: .unsupported, evidence: [evidence[35]], notes: "追加投影は読取専用。変更・新規保存を拒否し、未変更部分は保持。"),
                .init(feature: "ANI-002", profile: .ooxmlTransitional, operation: .edit, status: .unsupported, evidence: [evidence[35]], notes: "追加投影は読取専用。変更・新規保存を拒否し、未変更部分は保持。"),
                .init(feature: "ANI-005", profile: .ooxmlTransitional, operation: .edit, status: .unsupported, evidence: [evidence[35]], notes: "追加投影は読取専用。変更・新規保存を拒否し、未変更部分は保持。"),
                .init(feature: "MED-001", profile: .ooxmlTransitional, operation: .edit, status: .unsupported, evidence: [evidence[35]], notes: "追加投影は読取専用。変更・新規保存を拒否し、未変更部分は保持。"),
                .init(feature: "REV-001", profile: .ooxmlTransitional, operation: .edit, status: .unsupported, evidence: [evidence[35]], notes: "追加投影は読取専用。変更・新規保存を拒否し、未変更部分は保持。"),
                .init(feature: "PNT-004", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[36]], notes: "linear角度・path種類・stop順/色を保持。stop省略を継承補完せず、XML・診断を返す。"),
                .init(feature: "PNT-005", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[36]], notes: "pattern presetと前景/背景色。描画なし。"),
                .init(feature: "PNT-006", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[36]], notes: "内部/外部画像参照、crop、tileの有無、stretch詳細はXML。外部取得なし。"),
                .init(feature: "IMG-003", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[36]], notes: "srcRectの直接倍率と負値。形状mask・描画なし。"),
                .init(feature: "TBL-004", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[36]], notes: "四辺と対角線の直接stroke/noFill・XML。table styleによる実効罫線は未計算。"),
                .init(feature: "ANI-001", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[37]], notes: "直接効果名・namespace、方向等はXML。固有効果の再生なし。"),
                .init(feature: "ANI-002", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[37]], notes: "速度・クリック進行・進行時刻と拡張duration(ms)。未指定を補完しない。"),
                .init(feature: "ANI-005", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[37]], notes: "timingのnamespace付き木・属性・対象shape ID。トリガー/タイムライン評価なし。"),
                .init(feature: "MED-001", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[37]], notes: "audio/video/Office mediaの内部/外部参照とcontent typeを投影。Strict証拠は埋込音声に限定し、動画producer・再生は未検証。"),
                .init(feature: "REV-001", profile: .ooxmlStrict, operation: .read, status: .partial, evidence: [evidence[37]], notes: "従来コメントの本文・作者・日時字句・位置(pt)とXML。返信・mentions等の新形式は未解釈。"),
                .init(feature: "PNT-004", profile: .ooxmlStrict, operation: .edit, status: .unsupported, evidence: [evidence[38]], notes: "追加投影は読取専用。変更・新規保存を拒否し、未変更部分は保持。"),
                .init(feature: "PNT-005", profile: .ooxmlStrict, operation: .edit, status: .unsupported, evidence: [evidence[38]], notes: "追加投影は読取専用。変更・新規保存を拒否し、未変更部分は保持。"),
                .init(feature: "PNT-006", profile: .ooxmlStrict, operation: .edit, status: .unsupported, evidence: [evidence[38]], notes: "追加投影は読取専用。変更・新規保存を拒否し、未変更部分は保持。"),
                .init(feature: "IMG-003", profile: .ooxmlStrict, operation: .edit, status: .unsupported, evidence: [evidence[38]], notes: "追加投影は読取専用。変更・新規保存を拒否し、未変更部分は保持。"),
                .init(feature: "ANI-001", profile: .ooxmlStrict, operation: .edit, status: .unsupported, evidence: [evidence[38]], notes: "追加投影は読取専用。変更・新規保存を拒否し、未変更部分は保持。"),
                .init(feature: "ANI-002", profile: .ooxmlStrict, operation: .edit, status: .unsupported, evidence: [evidence[38]], notes: "追加投影は読取専用。変更・新規保存を拒否し、未変更部分は保持。"),
                .init(feature: "ANI-005", profile: .ooxmlStrict, operation: .edit, status: .unsupported, evidence: [evidence[38]], notes: "追加投影は読取専用。変更・新規保存を拒否し、未変更部分は保持。"),
                .init(feature: "MED-001", profile: .ooxmlStrict, operation: .edit, status: .unsupported, evidence: [evidence[38]], notes: "追加投影は読取専用。変更・新規保存を拒否し、未変更部分は保持。"),
                .init(feature: "REV-001", profile: .ooxmlStrict, operation: .edit, status: .unsupported, evidence: [evidence[38]], notes: "追加投影は読取専用。変更・新規保存を拒否し、未変更部分は保持。"),
                .init(feature: "REV-002", profile: .ooxmlTransitional, operation: .read, status: .preserveOnly, evidence: [evidence[40]], notes: "新形式コメントのpart/XML/参照を記述として返す。返信・解決・mentionsの意味モデルは未提供。"),
            ]
        default: return []
        }
    }
}
