#!/usr/bin/env python3
"""Generate fictional interoperability fixtures using python-pptx (MIT), never library output."""
import base64, json, zipfile, struct, zlib
from pathlib import Path
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.shapes import MSO_SHAPE, MSO_CONNECTOR
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
from pptx.chart.data import CategoryChartData
from pptx.enum.chart import XL_CHART_TYPE

root = Path(__file__).resolve().parents[1] / 'Tests/SwiftSlidesTests/Fixtures'
root.mkdir(parents=True, exist_ok=True)
p = Presentation(); p.slide_width = Inches(13.333333); p.slide_height = Inches(7.5)
p.core_properties.title = 'Fictional strategy'; p.core_properties.author = 'Fixture Author'; p.core_properties.last_modified_by = 'Fixture Generator'
s = p.slides.add_slide(p.slide_layouts[6]); s.name = 'Strategy'
a = s.shapes.add_textbox(Pt(40),Pt(30),Pt(600),Pt(60)); a.name = 'Headline'
t = a.text_frame; t.clear(); t.margin_left = Pt(8); t.margin_top = Pt(6)
par = t.paragraphs[0]; par.alignment = PP_ALIGN.CENTER
run = par.add_run(); run.text = '売上成長'; run.font.name = 'Aptos'; run.font.size = Pt(28); run.font.bold = True; run.font.color.rgb = RGBColor.from_string('2364AA'); run.hyperlink.address = 'https://example.com/strategy'
run = par.add_run(); run.text = ' — 90 days'; run.font.italic = True
shape = s.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE,Pt(60),Pt(140),Pt(240),Pt(100)); shape.name = 'Initiative'; shape.fill.solid(); shape.fill.fore_color.rgb = RGBColor.from_string('F4F6F8'); shape.line.color.rgb = RGBColor.from_string('2364AA'); shape.line.width = Pt(2); shape.text = '顧客集中'
c = s.shapes.add_connector(MSO_CONNECTOR.STRAIGHT,Pt(320),Pt(190),Pt(420),Pt(190)); c.name = 'Flow'; c.line.width = Pt(2)
shape = s.shapes.add_shape(MSO_SHAPE.CHEVRON,Pt(440),Pt(140),Pt(200),Pt(100)); shape.name = 'Decision'; shape.text = '実行'
table = s.shapes.add_table(2,3,Pt(60),Pt(300),Pt(600),Pt(100)).table
for i,row in enumerate([['施策','担当','指標'],['標準化','運用','作業時間']]):
 for j,value in enumerate(row): table.cell(i,j).text = value
s.notes_slide.notes_text_frame.text = '架空データの提案資料です。'
# A valid tiny PNG, generated bytes only.
image = root/'fixture.png'
def chunk(kind, payload): return struct.pack('>I',len(payload))+kind+payload+struct.pack('>I',zlib.crc32(kind+payload)&0xffffffff)
image.write_bytes(b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR',struct.pack('>IIBBBBB',1,1,8,6,0,0,0))+chunk(b'IDAT',zlib.compress(b'\x00\x23\x64\xaa\xff'))+chunk(b'IEND',b''))
s.shapes.add_picture(str(image),Pt(800),Pt(30),Pt(24),Pt(24))
g = s.shapes.add_group_shape(); g.name = 'Grouped'; g.shapes.add_shape(MSO_SHAPE.RECTANGLE,Pt(720),Pt(180),Pt(60),Pt(60)).text = 'A'; g.shapes.add_shape(MSO_SHAPE.OVAL,Pt(790),Pt(180),Pt(60),Pt(60)).text = 'B'
s2 = p.slides.add_slide(p.slide_layouts[6]); s2.name = 'Metrics'
data = CategoryChartData(); data.categories = ['Q1','Q2']; data.add_series('Revenue',[10,14]); s2.shapes.add_chart(XL_CHART_TYPE.COLUMN_CLUSTERED,Pt(60),Pt(80),Pt(500),Pt(300),data)
s2.shapes.add_textbox(Pt(60),Pt(30),Pt(500),Pt(40)).text = 'Metrics'
p.write(root/'python-pptx.pptx')
# Oracle is read through python-pptx, not SwiftSlides or its fixture XML parser.
q = Presentation(root/'python-pptx.pptx')
oracle = {'producer':'python-pptx','slides':len(q.slides),'width':q.slide_width/12700,'height':q.slide_height/12700,'title':q.core_properties.title,'headline':q.slides[0].shapes[0].text,'font':q.slides[0].shapes[0].text_frame.paragraphs[0].runs[0].font.name,'font_size':q.slides[0].shapes[0].text_frame.paragraphs[0].runs[0].font.size.pt,'table':[[cell.text for cell in row.cells] for row in q.slides[0].shapes[4].table.rows]}
(root/'producer-oracle.json').write_text(json.dumps(oracle,ensure_ascii=False,indent=2)+'\n')
with zipfile.ZipFile(root/'python-pptx.pptx') as z: parts={n:z.read(n) for n in z.namelist()}
def save(name,values,method=zipfile.ZIP_DEFLATED):
 with zipfile.ZipFile(root/name,'w',compression=method) as z:
  for n,b in values.items(): z.writestr(n,b)
save('stored.pptx',parts,zipfile.ZIP_STORED)
strict = {}
for n,b in parts.items():
 if n.endswith(('.xml','.rels')):
  for old,new in [(b'http://schemas.openxmlformats.org/presentationml/2006/main',b'http://purl.oclc.org/ooxml/presentationml/main'),(b'http://schemas.openxmlformats.org/drawingml/2006/main',b'http://purl.oclc.org/ooxml/drawingml/main'),(b'http://schemas.openxmlformats.org/officeDocument/2006/relationships',b'http://purl.oclc.org/ooxml/officeDocument/relationships')]: b=b.replace(old,new)
 strict[n]=b
save('strict.pptx',strict)
relocated={}
for n,b in parts.items():
 if n.endswith(('.xml','.rels')): b=b.replace(b'/ppt/',b'/deck/').replace(b'"ppt/',b'"deck/')
 relocated[n.replace('ppt/','deck/',1) if n.startswith('ppt/') else n]=b
save('relocated.pptx',relocated)
unknown=parts.copy(); n='ppt/slides/slide1.xml'; unknown[n]=unknown[n].replace(b'<p:sld ',b'<p:sld xmlns:u="urn:fictional:extension" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="u" ',1).replace(b'</p:sld>',b'<p:extLst><p:ext uri="fixture"><u:data u:value="kept">Opaque payload</u:data></p:ext></p:extLst></p:sld>');unknown['ppt/media/opaque.bin']=b'fictional opaque bytes';save('unknown.pptx',unknown)
macro=parts.copy(); macro['[Content_Types].xml']=macro['[Content_Types].xml'].replace(b'application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml',b'application/vnd.ms-powerpoint.presentation.macroEnabled.main+xml').replace(b'</Types>',b'<Override PartName="/ppt/vbaProject.bin" ContentType="application/vnd.ms-office.vbaProject"/></Types>');macro['ppt/vbaProject.bin']=b'fictional inert macro placeholder';save('macro.pptm',macro)
with zipfile.ZipFile(root/'zip64.pptx','w') as z:
 for n,b in parts.items():
  with z.open(n,'w',force_zip64=True) as out: out.write(b)
with zipfile.ZipFile(root/'impress.odp','w') as z: z.writestr('mimetype','application/vnd.oasis.opendocument.presentation')
print('Generated fictional fixtures and independent oracle.')
